//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedDoctor
    {
        public int Id { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> DoctorFee { get; set; }
        public Nullable<int> DoctorReturningFee { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public string SatTime { get; set; }
        public string SunTime { get; set; }
        public string MonTime { get; set; }
        public string TueTime { get; set; }
        public string WedTime { get; set; }
        public string ThuTime { get; set; }
        public string FriTime { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual MedicalAccount MedicalAccount { get; set; }
    }
}
