//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAppointment
    {
        public int Id { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> ChamberId { get; set; }
        public string ChamberName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string MobileNo { get; set; }
        public string Schedule { get; set; }
        public string AppointDate { get; set; }
        public Nullable<int> AppointPrice { get; set; }
        public string PaymentMethod { get; set; }
        public string TrxId { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string Status { get; set; }
    }
}
