//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAppointOrder
    {
        public int OrderId { get; set; }
        public Nullable<int> ManageAppointId { get; set; }
        public Nullable<int> AppointAmount { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string PaymentMethod { get; set; }
        public string TrxId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> RemainingAppoint { get; set; }
        public Nullable<int> TotalAppoint { get; set; }
        public Nullable<bool> Expired { get; set; }
        public string Status { get; set; }
    }
}
