//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorChamberOrder
    {
        public int OrderId { get; set; }
        public int Id { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public Nullable<int> DoctorChamberId { get; set; }
        public string Name { get; set; }
        public string MedicalName { get; set; }
        public string ChamberName { get; set; }
        public Nullable<int> AppointAmount { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string PaymentMethod { get; set; }
        public string TrxId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> Expired { get; set; }
        public string Status { get; set; }
    }
}
