//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPostsVM
    {
        public int ForumPostId { get; set; }
        public string TopicName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Views { get; set; }
        public string PostDate { get; set; }
        public int TopicCategoryId { get; set; }
        public string TopicCategoryName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Name { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public string ContactPersonName { get; set; }
    }
}
