//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumPost()
        {
            this.ForumComments = new HashSet<ForumComment>();
        }
    
        public int ForumPostId { get; set; }
        public Nullable<int> TopicCategoryId { get; set; }
        public string TopicName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public string PostDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumComment> ForumComments { get; set; }
        public virtual MedicalAccount MedicalAccount { get; set; }
        public virtual TopicCategory TopicCategory { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
