//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDoctor
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }
        public string Speciality { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string BmdcReg { get; set; }
        public string OtherSpecification { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public string MedicalName { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public Nullable<int> DoctorFee { get; set; }
        public Nullable<int> DoctorReturningFee { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public string SatTime { get; set; }
        public string SunTime { get; set; }
        public string MonTime { get; set; }
        public string TueTime { get; set; }
        public string WedTime { get; set; }
        public string ThuTime { get; set; }
        public string FriTime { get; set; }
    }
}
