//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSupportApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDoctorChamber
    {
        public Nullable<int> DoctorId { get; set; }
        public string Name { get; set; }
        public string Speciality { get; set; }
        public string OtherSpecification { get; set; }
        public int Id { get; set; }
        public string ChamberName { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string ContactNo { get; set; }
        public string PhoneNo { get; set; }
        public string Fee { get; set; }
        public string ReturningFee { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public string SatTime { get; set; }
        public string SunTime { get; set; }
        public string MonTime { get; set; }
        public string TueTime { get; set; }
        public string WedTime { get; set; }
        public string ThuTime { get; set; }
        public string FriTime { get; set; }
    }
}
